<a href="https://colab.research.google.com/github/kanikaguptakk/Books-Python/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
'''
list can store only 1 D array(float,integer,string,boolean) but importing numpy array we can store multidimensional array
'''
import numpy as np
a=np.array([3,4,5,6])
print(a)

b=np.array([[4,3,5,6],[5,6,7,8]])
print(b)

c=np.array([[3,4,6,7],[5,6,7,8],[5,6,7,8]])
print(c)

'''
a is a numpy n-dimensional array

'''
type(a)

'''
size=number of elements in that array
'''
print(a.size)
print(b.size)
print(c.size)

'''
shape=number of rows and columns
'''
print(a.shape)
print(b.shape)
print(c.shape)

'''dtype=type of data present in the array
'''
print(a.dtype)
print(b.dtype)
print(c.dtype)

d=np.array([[4.5,2.4,5,4],[1.0,5,6,7],[7,8,9,10]])
print(d.dtype)
print(d.transpose())

'''
np.empty()
'''

[3 4 5 6]
[[4 3 5 6]
 [5 6 7 8]]
[[3 4 6 7]
 [5 6 7 8]
 [5 6 7 8]]
4
8
12
(4,)
(2, 4)
(3, 4)
int64
int64
int64
float64
[[ 4.5  1.   7. ]
 [ 2.4  5.   8. ]
 [ 5.   6.   9. ]
 [ 4.   7.  10. ]]
